# Generated by Django 3.0.6 on 2020-06-01 03:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 3, 3, 53, 457063, tzinfo=utc)),
        ),
    ]
